### ISSUE TITLE
About code usage rights

### ISSUE THREAD

**Issue by liuyuanhao** [som2603/IGAPack-PhaseField#2]
Hi Somdatta Goswami,

I am Jim,a college student.We team are working on a project related to PHT splines.I have a request. May I use your code for PHT splines?If you can let me use,I will express my deep gratitude to you.

Yours sincerely,
Jim

**Comment by somdattagoswami** [comment]
Yes, you can use it.

**Comment by liuyuanhao** [comment]
Thank you so much！



---Original---

**Comment by liuyuanhao** [comment]
Hi Somdatta Goswami,

Thanks for your previous help.May I ask you a question？Can the code pack have the functions to compute the second derivative of the pht splines basis function?

Yours sincerely,
Jim

**Comment by somdattagoswami** [comment]
Hi Jim,

The code already has the subroutine for computing the second order
derivatives. You may use the fourth-order phase-field model, which would
use the second-order derivative model.
I hope I have answered your query!

With Regards,
Somdatta Goswami
