### ISSUE TITLE
Modifying crack size, number of cracks, location, and/or orientation

### ISSUE THREAD

**Issue by rperera12** [som2603/IGAPack-PhaseField#3]
Somdatta Goswami,
I am trying to use the provided phase-field models for different cases of crack size, location, and/orientation. 
Two of the provided configurations are centered crack, and edge crack, but I would like to change crack size, location, and orientation.
Also, is it possible to include domains with multiple cracks/defects?

**Comment by somdattagoswami** [comment]
Yeah you could do that by modifying the history field appropriately.
